Solving-Our-Meals/ukki-front

src/reset.scss
> 기본 구성 병합
<br/>
#
<br/>
> 
<br/>
=> [TEST][Basic]기본 구성 병합

package-lock.json, src/user/pages/signup/css/Signup.css, src/user/pages/signup/pages/Signup.js
> 회원가입 페이지 구현(미완성)
<br/>
#5
<br/>
> 
<br/>
=> [FEATURE][Signup]회원가입 페이지 구현(미완성)

src/App.js, src/common/inquiry/components/StoreDoInquiry.js, src/common/inquiry/components/StoreInquiryEnter.js, src/common/inquiry/components/StoreInquiryList.js, src/common/inquiry/components/UserDoInquiry.js, src/common/inquiry/css/doinquiry.css, src/common/inquiry/css/storeInquiryEnter.css
> 가게 문의 이동
<br/>
#44 
<br/>
> 
<br/>
=> [FEATURE][inquiry] 가게문의이동 모달

src/App.js, src/common/inquiry/api/inquiryListAPI.js, src/common/inquiry/api/reportListAPI.js, src/common/inquiry/components/StoreDoInquiry.js, src/common/inquiry/components/StoreInquiryEnter.js, src/common/inquiry/components/StoreInquiryList.js, src/common/inquiry/components/UserDoInquiry.js, src/common/inquiry/css/StoreInquiryList.css, src/common/inquiry/css/doinquiry.css, src/common/inquiry/css/storeInquiryEnter.css
> 가게문의 리스트 완성했습니다.
<br/>
#48 
<br/>
> 
페이징 처리에서 보이는 숫자 제한빼고 다 완료했습니다. 다음에는 상세진행 할 예정입니다.
<br/>
=> [FEATURE][Inquiry] 가게문의리스트

src/common/inquiry/components/StoreInquiryList.js, src/common/inquiry/css/StoreInquiryList.css, src/common/inquiry/css/doinquiry.css
> 문의리스트 반응형 및 페이징 수정 끝입니다.
<br/>
#48 
<br/>
> 
<br/>
=> [FEATURE][Inquiry] 문의 리스트 반응형 및 수정

package-lock.json, src/common/inquiry/api/reportInfoAPI.js, src/common/inquiry/api/reportListAPI.js, src/common/inquiry/components/AgreementModal.js, src/common/inquiry/components/ResultSmallModal.js, src/common/inquiry/components/StoreDoInquiry.js, src/common/inquiry/components/StoreInquiryInfo.js, src/common/inquiry/components/StoreInquiryList.js, src/common/inquiry/components/StoreReportInfo.js, src/common/inquiry/components/StoreUpdateReport.js, src/common/inquiry/css/AgreementModal.css, src/common/inquiry/css/StoreInquiryInfoMiddle.css, src/common/inquiry/css/StoreInquiryList.css, src/common/inquiry/css/doinquiry.css
> 리뷰 신고 상세보기, 수정, 삭제 완료했습니다.
<br/>
#70 
<br/>
> 
<br/>
=> [FEATURE][Report] 가게 리뷰 신고 상세

package-lock.json, src/user/pages/login/css/Login.css, src/user/pages/login/pages/Login.js, src/user/pages/signup/css/Signup.css, src/user/pages/signup/pages/Signup.js
> 없거나 빠진 부분 수정하고 약간 부족한 부분 손봤습니다.
<br/>
#69 
<br/>
> 
<br/>
=> [FIX][SomeFix]회원가입 & 로그인 디테일 수정

src/common/floatingBar/css/floatingbar.module.css, src/common/footer/css/footer.module.css, src/common/footer/css/footer.module.scss, src/user/layouts/UserLayout.js, src/user/layouts/css/userlayout.module.css, src/user/layouts/css/userlayout.module.scss, src/user/pages/login/css/reset.css, src/user/pages/storedetail/components/Calendar.js, src/user/pages/storedetail/css/banner.module.css, src/user/pages/storedetail/css/reservation.module.css, src/user/pages/storedetail/css/reservation.module.scss, src/user/pages/storedetail/css/storedetail.module.css, src/user/pages/storedetail/pages/ReservationInfo.js
> 가게 상세 페이지 달력 today 수정
<br/>
#77 
<br/>
> 가게 상세 페이지 달력 today 수정했습니다.
<br/>
=> [FEATURE][StoreDetail] 가게 상세 페이지 달력 today 수정

src/user/pages/main/component/Map.css, src/user/pages/main/component/Map.scss, src/user/pages/main/css/main.css, src/user/pages/storedetail/components/Calendar.js, src/user/pages/storedetail/css/reservation.module.css, src/user/pages/storedetail/css/reservation.module.scss, src/user/pages/storedetail/css/storedetail.module.css, src/user/pages/storedetail/pages/ReservationInfo.js, src/user/pages/storedetail/pages/StoreDetail.js
> 가게 상세 페이지 예약 가능 시간 구현
<br/>
#95 
<br/>
> 가게 상세 페이지 예약 가능 시간 구현 중입니다.
<br/>
=> [FEATURE][StoreDetail] 가게 상세 페이지 예약 가능 시간 구현

package-lock.json, src/user/pages/signup/pages/Signup.js
> 백엔드에서 받아올 error 값에 대해서 수정이 있었습니다.
<br/>
#97 
<br/>
> 
<br/>
=> [FIX][Noshow]백엔드 노쇼 로직을 위한 약간의 수정

src/common/floatingBar/css/floatingbar.module.css, src/common/footer/css/footer.module.css, src/common/footer/css/reset.module.css, src/common/header/css/header.css, src/common/header/css/reset.css, src/common/inquiry/css/reset.css, src/common/reset/reset.css, src/user/pages/find/css/reset.css, src/user/pages/login/css/reset.css, src/user/pages/main/component/Map.css, src/user/pages/main/css/main.css, src/user/pages/signup/css/reset.css, src/user/pages/storedetail/components/CreateReview.js, src/user/pages/storedetail/css/banner.module.css, src/user/pages/storedetail/css/createReview.module.css, src/user/pages/storedetail/css/createReview.module.scss, src/user/pages/storedetail/css/menu.module.css, src/user/pages/storedetail/css/profile.module.css, src/user/pages/storedetail/css/reservation.module.css, src/user/pages/storedetail/css/review.module.css, src/user/pages/storedetail/css/storedetail.module.css, src/user/pages/storedetail/pages/Review.js, src/user/pages/storedetail/pages/UserStorePage.js
> 가게 상세 페이지 리뷰 작성하기 레이아웃
<br/>
#126 
<br/>
> 가게 상세 페이지 리뷰 작성하기 레이아웃 구현 중
<br/>
=> [FEATURE][StoreDetail] 가게 상세 페이지 리뷰 작성하기 레이아웃

.github/team_rules/team_rules/team_rules.md, package-lock.json, src/user/pages/find/css/Find.module.css, src/user/pages/find/pages/Find.js, src/user/pages/login/css/Login.module.css, src/user/pages/login/pages/Login.js, src/user/pages/signup/css/Signup.module.css
> CSS 문제가 있었던 부분을 다듬고 수정했습니다.
> 반응형도 엉망이어서 나아보이게 수정했습니다.
<br/>
#129 
<br/>
> 병합 후 문제생긴건 몇몇 부분의 styles로 넣은 모듈이 누락된 것이었고 아무리봐도 반응형은 엉망이라 scale로 깔끔하게 바꿨습니다. 다만 이게 반응형이 맞는지 모르겠습니다.
처음부터 반응형 구성할때는 더 생각을 깊게 구성해야하지 않나 싶습니다.
<br/>
=> [FIX][FixAllCSS]CSS 전반적으로 전체 수정

.github/team_rules/team_rules/team_rules.md, package-lock.json, src/user/pages/find/css/Find.module.css, src/user/pages/find/pages/Find.js, src/user/pages/login/css/Login.module.css, src/user/pages/login/pages/Login.js, src/user/pages/signup/css/Signup.module.css, src/user/pages/signup/pages/Signup.js
> 스크롤을 다 내려야만 체크가 가능하게 수정했습니다.
<br/>
#123
<br/>
> 체크박스 관련 스크롤 조건만 추가했습니다.
<br/>
=> [FEATURE][AddTermsCheckboxCondition]약관 체크박스 조건 추가

.github/team_rules/team_rules/team_rules.md, package-lock.json, src/common/header/components/Header.js, src/user/pages/find/css/Find.module.css, src/user/pages/find/pages/Find.js, src/user/pages/login/css/Login.module.css, src/user/pages/login/pages/Login.js, src/user/pages/signup/css/Signup.module.css, src/user/pages/signup/pages/Signup.js
> 로그인되어 토큰이 존재하면 로그아웃 버튼이 나타나고 그렇지 않으면 로그인과 회원가입이 나타날 수 있도록 변경했습니다.
> 로그아웃하면 메인화면으로 돌아가고 리다이렉트를 한번 더 시켜서 깔끔하게 정리했습니다.
> 리다이렉트 시키지 않아도 제거되지만 뭔가 로그아웃한 느낌이 나지않아서 추가했습니다.
<br/>
#130 
<br/>
> 로그인 후에 토큰이 담겨있고 로그아웃 후에 토큰이 제거됨을 확인했으며 로그인 회원가입과 로그아웃 상태를 확인했습니다.
<br/>
=> [FEATURE][AddLogout]헤더에 로그아웃 추가

src/admin/pages/dashboard/api/DashboardAPI.js, src/admin/pages/dashboard/components/MonthlyNoshow.js, src/admin/pages/dashboard/components/MonthlyStores.js, src/admin/pages/dashboard/components/TodayRes.js, src/admin/pages/dashboard/components/TotalStores.js, src/admin/pages/dashboard/components/WeeklyRes.js, src/admin/pages/dashboard/css/AdminDashboard.css, src/admin/pages/dashboard/pages/AdminDashboard.js
> 관리자 대시보드 그래프 만드는중입니다.
<br/>
#134 
<br/>
> 
<br/>
=> [FEATURE][ADMIN] 관리자 대시보드 그래프

src/admin/components/css/AdminNavBar.css, src/admin/layouts/css/AdminLayout.css, src/admin/pages/dashboard/api/DashboardAPI.js, src/admin/pages/dashboard/components/MonthlyNoshow.js, src/admin/pages/dashboard/components/MonthlyStores.js, src/admin/pages/dashboard/components/ProcessingInquiry.js, src/admin/pages/dashboard/components/TodayRes.js, src/admin/pages/dashboard/components/WeeklyRes.js, src/admin/pages/dashboard/css/AdminDashboard.css, src/admin/pages/dashboard/css/reset.css, src/admin/pages/dashboard/pages/AdminDashboard.js, src/user/pages/mypage/pages/MyProfile.js
> 관리자 대시보드 완료입니다.
<br/>
#134 
<br/>
> 
<br/>
=> [FEATURE][ADMIN] 관리자 대시보드 완료

package-lock.json, src/admin/components/AdminAgreementModal.js, src/admin/components/AdminResultModal.js, src/admin/components/css/AgreementModal.css, src/admin/components/css/reset.css, src/admin/pages/user/css/UserInfo.module.css, src/admin/pages/user/pages/UserInfo.js
> 관리자 측에서 회원 닉네임 수정 및 삭제 기능
<br/>
#176 
<br/>
> 프로필과 뱃지는 마이페이지랑 동일해서 마이페이지 양식 정하고 바로 넣겠습니다.
<br/>
=> [FEATURE][ADMIN] 회원 수정 및 삭제

src/user/pages/storedetail/components/Calendar.js, src/user/pages/storedetail/components/CreateReview.js, src/user/pages/storedetail/components/Menu.js, src/user/pages/storedetail/css/menu.module.css, src/user/pages/storedetail/css/menu.module.scss, src/user/pages/storedetail/css/storedetail.module.css, src/user/pages/storedetail/css/storedetail.module.scss, src/user/pages/storedetail/pages/ReservationInfo.js, src/user/pages/storedetail/pages/StoreDetail.js, src/user/pages/storedetail/pages/UserStorePage.js
> 가게 상세페이지 전체적인 수정
<br/>
#181 
<br/>
> 오늘 대표님이 피드백 주신 내용을 기반으로 수정 중에 있습니다.
<br/>
=> [FIX][StoreDetail] 가게 상세페이지 전체적인 수정

package-lock.json, src/admin/pages/store/pages/AdminStore.js, src/admin/pages/user/api/UserListAPI.js, src/admin/pages/user/css/UserInfo.module.css, src/admin/pages/user/css/UserList.module.css, src/admin/pages/user/pages/UserInfo.js, src/admin/pages/user/pages/UserList.js, src/admin/route/AdminRoutes.js
> 회원번호 삭제 및 사장님 회원등록 버튼 삭제 그리고 일반회원만 나오도록 수정
<br/>
#183 
<br/>
> 
<br/>
=> [FIX][ADMIN] 회원 수정사항

src/user/pages/find/css/Find.module.css, src/user/pages/login/css/Login.module.css, src/user/pages/signup/css/Signup.module.css
> 파이어폭스를 위한 CSS 수정
<br/>
#180 
<br/>
> 파이어폭스 전용 css 추가
<br/>
=> [FIX][FixCssForFirefox]파이어폭스 전용 CSS 수정(크로스웹)

package-lock.json, src/admin/pages/store/api/AddrToCoordinate.js, src/admin/pages/store/css/StoreEdit.module.css, src/admin/pages/store/css/StoreInfo.module.css, src/admin/pages/store/css/menu.module.css, src/admin/pages/store/pages/StoreEdit.js, src/admin/pages/store/pages/StoreInfo.js
> 열심히 하는중...
<br/>
#192 
<br/>
> 
<br/>
=> [FEATURE][ADMIN] 가게 수정 페이지

package-lock.json, src/user/pages/find/css/Find.module.css
> Find.module.css의 전역 설정 관련 CSS 수정입니다.
<br/>
#202 
<br/>
> 
<br/>
=> [FIX][FixCSS]전역 설정 관련 CSS 수정

package-lock.json, src/admin/pages/store/api/AddrToCoordinate.js, src/admin/pages/store/css/StoreEdit.module.css, src/admin/pages/store/css/StoreInfo.module.css, src/admin/pages/store/css/menu.module.css, src/admin/pages/store/pages/StoreEdit.js, src/admin/pages/store/pages/StoreInfo.js
> 가게 정보 수정 완료했습니다.
<br/>
#192
<br/>
> 
<br/>
=> [FEATURE][ADMIN] 가게 정보 수정

package-lock.json, src/admin/pages/store/api/AddrToCoordinate.js, src/admin/pages/store/components/Banner.js, src/admin/pages/store/css/StoreEdit.module.css, src/admin/pages/store/css/StoreInfo.module.css, src/admin/pages/store/css/menu.module.css, src/admin/pages/store/pages/StoreEdit.js, src/admin/pages/store/pages/StoreInfo.js
> 가게 삭제 페이지 조금 수정해야합니다.
<br/>
#192 
<br/>
> 
<br/>
=> [FEATURE][ADMIN] 가게 삭제

src/admin/pages/store/pages/StoreEdit.js, src/admin/pages/store/pages/StoreInfo.js
> 가게 수정 및 삭제 완료입니다.
<br/>
#192 
<br/>
> 
<br/>
=> [FEATURE][ADMIN] 가게 수정 삭제

package-lock.json, src/user/pages/mypage/css/Reservation.module.css, src/user/pages/mypage/css/Review.module.css, src/user/pages/mypage/pages/Reservation.js, src/user/pages/mypage/pages/Review.js
> 피드백 받은 마이페이지 CSS 수정
<br/>
#227 
<br/>
> 생각해보니 피그마대로 가야하는데 제가 다르게 만들었다보니 최대한 피그마대로 변경했습니다.
> 그리고 앞으로 피드백은 카카오톡보다 풀리에 코멘트 달때 사진보고 해주시고 세부적인 피드백이나 궁금증 등은 메신저 등으로 나누면 좋을 것 같습니다.
> 추가로 피그마는 좌측 정렬인데 피드백이 중앙 정렬을 원하셔서 중앙 정렬입니다.
> 버튼은 원래 마우스 올리면 나오게하려고 했는데 기능이 있는지 모를 수 있다 생각해 아에 보이게 변경했습니다.
> 페이지네이션도 피그마랑 동일하게 했고 없는 페이지는 화살표 안나오게 변경했으면 좋겠어요 ~
<br/>
예약 리스
리뷰
탭 수정 (간격이 피그마보다 넓어서 수정했습니다.)
=> [FIX][FixMypageCSS]마이페이지 CSS 수정

src/admin/pages/reservation/api/ReservationEndInfoAPI.js, src/admin/pages/reservation/api/ReservationListAPI.js, src/admin/pages/reservation/api/ReservationTodayInfoAPI.js, src/admin/pages/reservation/css/ReservationInfo.module.css, src/admin/pages/reservation/css/ReservationList.module.css, src/admin/pages/reservation/pages/AdminReservation.js, src/admin/pages/reservation/pages/ReservationEndInfo.js, src/admin/pages/reservation/pages/ReservationList.js, src/admin/pages/reservation/pages/ReservationTodayInfo.js, src/admin/pages/store/api/GetBannerAPI.js, src/admin/pages/store/css/StoreList.module.css, src/admin/pages/store/pages/StoreEdit.js, src/admin/pages/store/pages/StoreList.js, src/admin/pages/user/css/UserList.module.css, src/admin/pages/user/pages/UserList.js, src/admin/route/AdminRoutes.js
> 상세조회 및 삭제 , 페이지네이션 수정
<br/>
#234 
<br/>
> 원래는 조회까지 하려고했는데 삭제도 만들어버려서 한번에 올렸습니다.
지금 상세쪽 내용 보시면 넣을 내용이 너무 없어서 그냥 qr코드를 이 예약 상세에다가 이미지로 넣어버릴까하는데 여러분들 생각은 어떠신가요?
좀 더 넣을 내용이 있을 것 같으면 적극적으로 말해주세요.
<br/>
=> [FEATURE][ADMIN] 예약 상세조회 및 삭제

src/common/floatingBar/css/floatingbar.module.css, src/common/footer/css/footer.module.css, src/common/footer/css/reset.module.css, src/common/header/css/header.css, src/common/header/css/reset.css, src/common/inquiry/css/reset.css, src/common/reset/reset.css, src/user/pages/find/css/reset.css, src/user/pages/login/css/reset.css, src/user/pages/main/component/Map.css, src/user/pages/main/css/main.css, src/user/pages/mypage/css/reset.css, src/user/pages/reservation/css/kakaoMap.module.css, src/user/pages/reservation/css/profile.module.css, src/user/pages/reservation/css/representativePhoto.module.css, src/user/pages/reservation/css/reservation.module.css, src/user/pages/reservation/css/reservationInfo.module.css, src/user/pages/reservation/css/termsOfUse.module.css, src/user/pages/search/css/search.module.css, src/user/pages/signup/css/reset.css, src/user/pages/storedetail/css/banner.module.css, src/user/pages/storedetail/css/createReview.module.css, src/user/pages/storedetail/css/kakaoMap.module.css, src/user/pages/storedetail/css/menu.module.css, src/user/pages/storedetail/css/profile.module.css, src/user/pages/storedetail/css/reservation.module.css, src/user/pages/storedetail/css/review.module.css, src/user/pages/storedetail/css/review.module.scss, src/user/pages/storedetail/css/storedetail.module.css, src/user/pages/storedetail/pages/Review.js
> 가게 상세페이지 리뷰 삭제 완성
<br/>
#256 
<br/>
> 가게 상세페이지 리뷰 삭제 완성
<br/>
=> [FEATURE][StoreDetail] 가게 상세페이지 리뷰 삭제 완성

src/admin/pages/review/api/ReviewInfoAPI.js, src/admin/pages/review/css/ReviewInfo.module.css, src/admin/pages/review/pages/ReviewInfo.js, src/admin/pages/review/pages/ReviewList.js, src/admin/route/AdminRoutes.js
> 리뷰 상세보기
<br/>
#250 
<br/>
> 
<br/>
=> [FEATURE][ADMIN] 리뷰 상세보기

src/admin/pages/review/api/ReviewInfoAPI.js, src/admin/pages/review/css/ReviewInfo.module.css, src/admin/pages/review/pages/ReviewInfo.js, src/admin/pages/review/pages/ReviewList.js, src/admin/route/AdminRoutes.js
> 리뷰삭제 완료입니다.
<br/>
#270 
<br/>
> 
<br/>
=> [FEATURE][ADMIN] 리뷰 삭제

src/user/pages/search/Search.js, src/user/pages/search/components/Profile.js, src/user/pages/storedetail/components/Banner.js
> 검색 페이지 가게 프로필 구현
<br/>
#279 
<br/>
> 검색 페이지 가게 프로필 구현
<br/>
=> [FIX][Search] 검색 페이지 가게 프로필 구현

src/admin/pages/store/api/GetBannerAPI.js, src/admin/pages/store/api/GetMenuAPI.js, src/admin/pages/store/api/GetProfileAPI.js, src/admin/pages/store/components/Banner.js, src/admin/pages/store/components/Menu.js, src/admin/pages/store/components/Profile.js, src/admin/pages/store/pages/StoreEdit.js, src/admin/pages/store/pages/StoreInfo.js
> 기존 fetch로 불러오던 url이 바뀌어서 수정했습니다.
<br/>
#281 
<br/>
> 
<br/>
=> [FIX][ADMIN] 가게 이미지 fetch조정

src/user/pages/mypage/css/Inquiry.module.css, src/user/pages/mypage/pages/Inquiry.js, src/user/pages/mypage/pages/InquiryDetails.js, src/user/pages/mypage/pages/Reservation.js, src/user/pages/mypage/pages/Review.js, src/user/pages/mypage/route/Mypage.js
> 여러가지 피드백을 수정했습니다.
<br/>
#276 
<br/>
> 1. 마이페이지에서 불러올 정보 없을 때 문제
병합 전엔 문제가 없었으나 백을 수정하지 않으면 해결되지 않아 연계해서 수정완료했습니다.
프론트에도 만들어놔서 문제 없을 것같지만 문제생기면 다시 말씀해주세요.
문제가 생기면 먼저 프론트 쪽 F12(개발자 도구)로 먼저 확인해주시면 감사하겠습니다.
<hr>
> 2. 피드백은 없었으나 CHECK 관련 로직에서 웹상 오류 발생 (백 오류 X) 수정
변수에 대한 문제로 그 부분은 해결했고, 리액트 특성 상 새로고침 후엔 해결됩니다.
(나중에 문제될거 같으면 새로고침이나 정보 불러오는 로직을 추가하겠습니다.)
> 3. 버튼 위치 수정
버튼 위치 수정 및 전체적으로 변경했습니다.
> 4. 글씨체 수정
padding 값 동일하게 하자고 해서 수정했고, 폰트크기는 동일합니다.
확인과정에서 폰트체가 다름 확인하여 말씀드렸고, line-height 같은 경우엔 CSS 설정에 따라 달라지기에 말씀해주신 값은
문제가 생긴다 판단하여 최대한 동일하게 했습니다.
<br/>
=> [FIX][FixMypageFeedback]마이페이지 피드백 수정

package-lock.json, src/user/pages/mypage/css/Inquiry.module.css, src/user/pages/mypage/pages/Inquiry.js, src/user/pages/mypage/pages/InquiryDetails.js
> 마이페이지 문의 모달입니다.
<br/>
#273 
<br/>
> 
<br/>
=> [FEATURE][MypageInquiryModal]마이페이지 문의 모달

package-lock.json, src/user/pages/mypage/css/Inquiry.module.css, src/user/pages/mypage/css/Review.module.css, src/user/pages/mypage/pages/Inquiry.js, src/user/pages/mypage/pages/InquiryDetails.js
> 미완성입니다. 경로 때문에 좀 보고 해야할 것 같아요.
> 바꿔야 할 수 있고 임시입니다.
<br/>
#275 
<br/>
> 
<br/>
=> [FEATURE][MypageFileDownAndUpload]마이페이지 파일 다운로드 및 업로드

package-lock.json, src/admin/pages/inquiry/api/ReportInfoAPI.js, src/admin/pages/inquiry/css/Inquiry.module.css, src/admin/pages/inquiry/css/InquiryList.module.css, src/admin/pages/inquiry/pages/InquiryInfo.js, src/admin/pages/inquiry/pages/InquiryList.js, src/admin/pages/inquiry/pages/ReportInfo.js
> 문의 조회, 수정, 삭제
<br/>
#285 
<br/>
> 이슈는 조회만 만들었는데 수정이랑 삭제도 여기다가 구현해버렸습니다...
<br/>
=> [FEATURE][ADMIN] 문의 조회, 수정, 삭제

package-lock.json, src/admin/pages/notice/css/NoticeInfo.module.css, src/admin/pages/notice/css/NoticeRegist.module.css, src/admin/pages/notice/pages/NoticeInfo.js, src/admin/pages/notice/pages/NoticeRegist.js, src/admin/route/AdminRoutes.js
> 공지사항 생성, 수정, 삭제
<br/>
#320 
<br/>
> 
<br/>
=> [FEATURE][ADMIN] 공지사항 생성, 수정, 삭제

src/common/error/css/error403.module.css, src/common/error/css/error404.module.css, src/common/error/css/error500.module.css, src/user/pages/info/css/footer.module.css, src/user/pages/info/css/footer.module.scss, src/user/pages/main/css/footer.module.css, src/user/pages/main/css/footer.module.scss, src/user/pages/search/css/footer.module.css, src/user/pages/search/css/footer.module.scss, src/user/pages/storedetail/css/footer.module.css, src/user/pages/storedetail/css/footer.module.scss, src/user/pages/storedetail/css/userStorePage.module.css
> Footer 레이아웃 수정
<br/>
#322 
<br/>
> Footer 레이아웃(CSS) 헤더에 맞게 색상 변경했고 크기도 조금 줄였습니다.
<br/>
=> [FIX][Footer] Footer 레이아웃 수정

src/common/error/css/error403.module.css, src/common/error/css/error404.module.css, src/common/error/css/error500.module.css, src/user/pages/info/css/footer.module.css, src/user/pages/info/css/footer.module.scss, src/user/pages/main/css/footer.module.css, src/user/pages/main/css/footer.module.scss, src/user/pages/reservation/components/KakaoMap.js, src/user/pages/reservation/css/kakaoMap.module.css, src/user/pages/reservation/css/kakaoMap.module.scss, src/user/pages/reservation/css/profile.module.css, src/user/pages/reservation/css/profile.module.scss, src/user/pages/reservation/css/representativePhoto.module.css, src/user/pages/reservation/css/representativePhoto.module.scss, src/user/pages/search/css/footer.module.css, src/user/pages/search/css/footer.module.scss, src/user/pages/storedetail/components/Calendar.js, src/user/pages/storedetail/css/footer.module.css, src/user/pages/storedetail/css/footer.module.scss, src/user/pages/storedetail/css/userStorePage.module.css
> 예약 페이지 카카오맵 수정
<br/>
#324 
<br/>
> 예약 페이지 카카오맵 수정했습니다.
길찾기, 큰지도 보기 빼고 주소만 뜨게 했습니다.
<br/>
=> [FIX][Reservation] 예약 페이지 카카오맵 수정

package-lock.json, src/user/pages/mypage/component/MyProfile.js, src/user/pages/mypage/css/MyProfile.module.css, src/user/pages/mypage/css/ReviewDetail.module.css, src/user/pages/mypage/pages/Review.js, src/user/pages/mypage/pages/ReviewDetail.js, src/user/pages/mypage/route/Mypage.js
> 마이페이지 상세
<br/>
#331 
<br/>
>모달이랑 버튼 CSS만 추가하면 끝입니다.
<br/>
=> [FEATURE][MypageDetail]마이페이지 상세

src/user/pages/mypage/pages/InquiryDetails.js
> 마이페이지 문의 파일 다운로드 시 기존 파일 제거 로직 및 다운로드 로직 추가
<br/>
#275 
<br/>
> 경로가 바뀌면 꼬일까봐 무서운데 일단 잘 됩니다.
<br/>
=> [FEATURE][MypageInquiryFiles]마이페이지 문의 파일 다운로드 시 기존 파일 제거 로직 및 다운로드 로직 추가

Dockerfile, package-lock.json, src/admin/pages/store/api/GetBannerAPI.js, src/admin/pages/store/pages/StoreEdit.js
> 가게 수정 시 주소 오류나는 부분 해결했습니다. 보내는 데이터 값이 서버측에서 받는 값과 일치하지 않아서 생기는 문제였습니다.
<br/>
#356 
<br/>
> docker만들기 위한 dockerfile이 같이 들어가있습니다.
<br/>
=> [FIX][ADMIN] 가게 수정 시 주소 오류

Dockerfile, package-lock.json, src/admin/pages/reservation/css/ReservationInfo.module.css, src/admin/pages/reservation/pages/ReservationEndInfo.js, src/admin/pages/reservation/pages/ReservationTodayInfo.js, src/admin/pages/store/api/GetBannerAPI.js, src/admin/pages/store/pages/StoreEdit.js
> 예약 상세조회 CSS 개선
<br/>
#358
<br/>
> css괜찮다고 느껴지시면 왼쪽으로 조금씩 옮기고 마무리하겠습니다.
<br/>
=> [FIX][ADMIN] 예약 상세조회 개선

docker-compose.local.yml, docker-compose.yml, nginx.conf, package-lock.json
> 만드는중
<br/>
#368 
<br/>
> 서버쪽에 연결은 완료했으나 프론트쪽에서 에러가 좀 나서 로컬에서 확인한 후에 진행할 예정입니다. 로컬에서 docker돌렸을 때 프론트에 접속이 되긴하지만 화면이 잘 안나오고 백은 잘 돌아갑니다. 내일 db랑 연결해서 해봐야할 것 같아요
<br/>
=> [FEATURE][DEPLOY] 배포 진행 중

src/store/layouts/BossLayout.js, src/user/pages/find/css/Find.module.css, src/user/pages/login/css/Login.module.css, src/user/pages/mypage/component/MyProfile.js, src/user/pages/mypage/css/Inquiry.module.css, src/user/pages/mypage/css/MyProfile.module.css, src/user/pages/mypage/css/Reservation.module.css, src/user/pages/mypage/css/ReservationDetail.module.css, src/user/pages/mypage/css/Review.module.css, src/user/pages/mypage/pages/Inquiry.js, src/user/pages/mypage/pages/InquiryDetails.js, src/user/pages/mypage/pages/ProfileInfo.js, src/user/pages/mypage/pages/Reservation.js, src/user/pages/mypage/pages/ReservationDetail.js, src/user/pages/mypage/pages/Review.js
> 마이페이지 조건부 버튼 생성
<br/>
#385 #273 
<br/>
> 조건부 렌더링을 통한 버튼 추가
<br/>
이건 보여드리려고 강조했습니다. 이런 느낌입니다.
횟수는 더미때문에 그래요.
=> [FEATURE][MypageReservation]마이페이지 조건부 버튼 생성 & 모달 수정

src/user/pages/mypage/pages/ProfileInfo.js
> 탈퇴에 없어진 부분이나 조정이 있었습니다.
<br/>
#397 
<br/>
> 
<br/>
=> [FIX][FixDeleteAccount]회원 탈퇴 수정에 맞춰 부족한 부분 조정

src/user/pages/mypage/pages/ProfileInfo.js, src/user/pages/mypage/pages/Reservation.js
> 마이페이지 예약 취소
<br/>
#401 
<br/>
> 마이페이지 예약 취소 기능
<br/>
=> [FEATURE][MypageDeleteReservation]마이페이지 예약 취소

src/user/pages/mypage/component/MyProfile.js, src/user/pages/mypage/css/ReservationDetail.module.css, src/user/pages/mypage/css/ReviewDetail.module.css, src/user/pages/mypage/pages/Inquiry.js, src/user/pages/mypage/pages/InquiryDetails.js, src/user/pages/mypage/pages/ProfileInfo.js, src/user/pages/mypage/pages/Reservation.js, src/user/pages/mypage/pages/ReservationDetail.js, src/user/pages/mypage/pages/Review.js, src/user/pages/mypage/pages/ReviewDetail.js, src/user/pages/mypage/route/Mypage.js
=> [FIX][FixReservationDetails]예약 상세 CSS 수정

src/user/pages/mypage/component/MyProfile.js, src/user/pages/mypage/css/Inquiry.module.css, src/user/pages/mypage/css/ProfileInfo.module.css, src/user/pages/mypage/css/Reservation.module.css, src/user/pages/mypage/css/ReservationDetail.module.css, src/user/pages/mypage/css/Review.module.css, src/user/pages/mypage/css/ReviewDetail.module.css, src/user/pages/mypage/pages/Inquiry.js, src/user/pages/mypage/pages/InquiryDetails.js, src/user/pages/mypage/pages/ProfileInfo.js, src/user/pages/mypage/pages/Reservation.js, src/user/pages/mypage/pages/ReservationDetail.js, src/user/pages/mypage/pages/Review.js, src/user/pages/mypage/pages/ReviewDetail.js, src/user/pages/mypage/route/Mypage.js
>이슈 들어가보면 어떤 피드백인지 써있습니다 !
<br/>
#394 
<br/>
> 
<br/>
=> [FIX][FixModalFeedback]피드백에 따른 모달 수정

src/store/pages/bossStore/pages/BossPage.js
> 30분 단위로 TBL_RES_POS_NUMBER에 들어가는 거 까지는 성공했는데 새로고침하면 가능인원이 다시 기본값(5)으로 돌아갑니다. 현재 url뒤에 :1이 붙어있어서 오류가 나는거 같은데 막상 클릭해보면 url에는 :1이 안붙어있어서 그게 어디서 붙어오는건지 찾는중입니다
<br/>
#411
<br/>
> 
<br/>
=> [FEATURE][BOSS] 사장님 페이지 시간별 예약 가능인원

src/user/pages/mypage/component/MyProfile.js, src/user/pages/mypage/css/Inquiry.module.css, src/user/pages/mypage/css/ProfileInfo.module.css, src/user/pages/mypage/css/Reservation.module.css, src/user/pages/mypage/css/ReservationDetail.module.css, src/user/pages/mypage/css/Review.module.css, src/user/pages/mypage/css/ReviewDetail.module.css, src/user/pages/mypage/pages/Inquiry.js, src/user/pages/mypage/pages/InquiryDetails.js, src/user/pages/mypage/pages/ProfileInfo.js, src/user/pages/mypage/pages/Reservation.js, src/user/pages/mypage/pages/ReservationDetail.js, src/user/pages/mypage/pages/Review.js, src/user/pages/mypage/pages/ReviewDetail.js, src/user/pages/mypage/route/Mypage.js
> 리렌더링 기능
<br/>
#406 
<br/>
> 예약 취소 후 우측 기본 컴포넌트인 프로필 쪽은 리렌더링 되지 않기 때문에 함께 리렌더링될 수 있도록 추가
<br/>
=> [FEATURE][Rerendering]리렌더링

package-lock.json, src/user/pages/mypage/pages/ProfileInfo.js, src/user/pages/mypage/pages/Review.js, src/user/pages/mypage/route/Mypage.js, src/user/pages/storedetail/components/Calendar.js, src/user/pages/storedetail/components/CreateReview.js
> 서버 배포를 위한 수정 및 리렌더링 보완
<br/>
#416 
<br/>
> 서버 배포로 인코딩 문제가 생긴 날짜를 고치고 시간의 초부분을 제거했습니다.
<br/>
=> [FIX][FixForServerAndRerendering]서버 배포를 위한 수정 및 리렌더링 보완

src/store/pages/bossStore/pages/BossPage.js
> 런타임 에러 수정
<br/>
#421
<br/>
> 
<br/>
=> [FIX][BOSS] 오류 수정

package-lock.json, src/App.js, src/common/authContext/AuthContext.js, src/common/authContext/PrivateRoute.js, src/user/pages/mypage/pages/ProfileInfo.js, src/user/pages/mypage/pages/Review.js, src/user/pages/mypage/route/Mypage.js, src/user/pages/storedetail/components/Calendar.js, src/user/pages/storedetail/components/CreateReview.js
> 유저 역할에 따른 페이지 이동
<br/>
#420 
<br/>
> 유저 페이지 이동 프론트에서 권한설정 - > 백엔드도 할 예정
<br/>
=> [FEATURE][UserRole]유저 역할에 따른 페이지 이동

src/common/header/components/BossHeader.js, src/user/layouts/UserLayout.js, src/user/pages/storedetail/components/Calendar.js, src/user/pages/storedetail/components/CreateReview.js, src/user/pages/storedetail/components/Profile.js
> 사장님 페이지, 가게 상세페이지 오류 해결
<br/>
#418 
<br/>
> 사장님 페이지, 가게 상세페이지 오류 해결
<br/>
=> [FIX][Total] 사장님 페이지, 가게 상세페이지 오류 해결

package-lock.json, src/common/authContext/AuthContext.js, src/config/api.config.js, src/user/pages/find/css/Find.module.css, src/user/pages/find/pages/Find.js, src/user/pages/login/pages/Login.js, src/user/pages/mypage/component/MyProfile.js, src/user/pages/mypage/pages/Inquiry.js, src/user/pages/mypage/pages/InquiryDetails.js, src/user/pages/mypage/pages/ProfileInfo.js, src/user/pages/mypage/pages/Reservation.js, src/user/pages/mypage/pages/ReservationDetail.js, src/user/pages/mypage/pages/Review.js, src/user/pages/mypage/pages/ReviewDetail.js, src/user/pages/mypage/route/Mypage.js, src/user/pages/signup/pages/Signup.js
> 서버 배포 설정
<br/>
#424
<br/>
> API_BASE_URL import 연결 완료
> 오프라인으로 서로 상의하고 fetch 부분 변경 및 fetch 헤더 삽입 완료
<br/>
=> [FIX][FixForServerDeployment]서버 배포 설정

src/config/api.config.js, src/store/layouts/BossLayout.js, src/store/pages/bossStore/pages/BossPage.js, src/user/pages/main/Main.js, src/user/pages/main/component/Map.js, src/user/pages/search/Search.js
=> [FIX][ALL] 서버 배포용 수정

src/config/api.config.js, src/store/pages/bossInquiry/pages/SpecificInquiry.js, src/user/pages/storedetail/components/CreateReview.js, src/user/pages/storedetail/pages/Review.js
> 가게 상세페이지 리뷰 작성 및 그 외 버그
<br/>
#435 
<br/>
> 가게 상세페이지 리뷰 작성 및 그 외 버그 해결 중입니다.
<br/>
=> [FIX][StoreDetail] 가게 상세페이지 리뷰 작성 및 그 외 버그

.github/workflows/deploy.yml
> GitHub Action 사용을 위한 deploy 수정
<br/>
#437 
<br/>
> 
<br/>
=> [FIX][DEPLOY] deploy 수정

src/config/api.config.js, src/user/pages/mypage/component/MyProfile.js, src/user/pages/mypage/pages/InquiryDetails.js
=> [FEATURE][ConnectGoolgleDrive]구글 드라이브 연결

src/user/pages/storedetail/components/CreateReview.js
> 가게 상세페에지 이미지 드라이브 연결
<br/>
#454 
<br/>
> 가게 상세페에지 이미지 드라이브 연결
<br/>
=> [FEATURE][StoreDetail] 가게 상세페에지 이미지 드라이브 연결

src/common/header/components/Header.js, src/config/api.config.js, src/user/pages/find/css/Find.module.css, src/user/pages/login/css/Login.module.css, src/user/pages/mypage/component/MyProfile.js, src/user/pages/mypage/pages/InquiryDetails.js, src/user/pages/signup/css/Signup.module.css, src/user/pages/signup/pages/Signup.js
> 로그인 시 헤더에 닉네임 삽입
<br/>
#409 #461
<br/>
> 
<br/>
=> [FEATURE][AddNicknameForHeader]로그인 시 헤더에 닉네임 삽입 & 문제있는 CSS 수정

src/config/api.config.js, src/store/pages/bossStore/pages/BossPage.js
> 예약인원 조정 새로고침해도 유지되게 하기
<br/>
#465
<br/>
> 
<br/>
=> [FEATURE][RESPOSNUM] 예약가능인원 조정

src/config/api.config.js, src/store/pages/bossStore/pages/BossPage.js, src/user/pages/search/Search.js
> 기존 인기검색어 오류 수정
Popular Searches: [버거, 버, ㅂ, 김치, 밥, 벅, ㄱ, 기, 김, 김ㅊ] -> [버거,김치,밥]
<br/>
#467
<br/>
> 
<br/>
=> [FIX][SEARCH] 인기검색어 수정

src/config/api.config.js
=> [][]메인 업데이트 URL 누락 수정

package-lock.json, src/App.js, src/admin/components/AdminHeader.js, src/common/authContext/UserRole.js, src/common/header/components/BossHeader.js, src/common/header/components/Header.js, src/user/pages/login/pages/Login.js, src/user/pages/main/Main.js, src/user/pages/mypage/component/MyProfile.js, src/user/pages/mypage/pages/Reservation.js, src/user/pages/mypage/pages/ReservationDetail.js, src/user/pages/storedetail/components/Calendar.js, src/user/pages/storedetail/components/CreateReview.js, src/user/pages/storedetail/components/Menu.js, src/user/pages/storedetail/components/Profile.js, src/user/pages/storedetail/components/test.js, src/user/pages/storedetail/pages/StoreDetail.js
> 문제점들 확인 후 수정완료
<br/>
#
<br/>
> 
<br/>
=> [FIX][ForComplement]문제있는 부분 여러가지 수정

src/common/header/css/header.css, src/user/pages/storedetail/components/CreateReview.js
> 리뷰 작성 권한 오류 해결
<br/>
#488 
<br/>
> 리뷰 작성 권한 오류 해결
<br/>
=> [FIX][StoreDetail] 리뷰 작성 권한 오류 해결

src/common/header/css/header.css, src/store/pages/bossInquiry/css/specificReviewModal.module.scss, src/store/pages/bossInquiry/css/totalInquiryPage.module.css, src/store/pages/bossInquiry/css/totalInquiryPage.module.scss, src/store/pages/bossNotice/components/BossTotalNotice.js, src/store/pages/bossNotice/css/bossSpecificNotice.module.css, src/store/pages/bossNotice/css/bossSpecificNotice.module.scss, src/store/pages/bossNotice/css/bossTotalNotice.module.css, src/store/pages/bossNotice/css/bossTotalNotice.module.scss, src/store/pages/bossStore/css/Sidebar.css, src/store/pages/bossStore/pages/BossPage.js, src/user/pages/reservation/css/representativePhoto.module.css, src/user/pages/reservation/css/representativePhoto.module.scss, src/user/pages/reservation/css/reservationInfo.module.css, src/user/pages/reservation/css/reservationInfo.module.scss, src/user/pages/reservation/css/termsOfUse.module.css, src/user/pages/reservation/css/termsOfUse.module.scss, src/user/pages/storedetail/components/CreateReview.js, src/user/pages/storedetail/css/createReview.module.css, src/user/pages/storedetail/css/createReview.module.scss, src/user/pages/storedetail/css/menu.module.css, src/user/pages/storedetail/css/menu.module.scss, src/user/pages/storedetail/css/profile.module.css, src/user/pages/storedetail/css/profile.module.scss, src/user/pages/storedetail/css/review.module.css, src/user/pages/storedetail/css/review.module.scss, src/user/pages/storedetail/pages/Review.js
> 리뷰 작성 시 예약 번호 선택
<br/>
#490 
<br/>
> 리뷰 작성 시 예약 번호 선택
<br/>
=> [FEATURE][StoreDetail] 리뷰 작성 시 예약 번호 선택

package-lock.json, src/store/layouts/BossLayout.js, src/store/pages/bossStore/pages/BossPage.js, src/user/pages/main/Main.js, src/user/pages/main/component/Map.js
> 마커클릭하고 에약하기 버튼 누르면 선택 안됬던 오류 해결
<br/>
#492
<br/>
> 
<br/>
=> [FIX][MAIN] 메인 가게 연결 수정 

src/common/inquiry/components/DoInquiry.js
> 문의하기 확인 눌렀을 시 페이지가 새로고침 되는 부분 해결
<br/>
#501 
<br/>
> 
<br/>
=> [FIX][INQUIRY] 문의하기 수정

src/store/layouts/css/bosslayout.module.css, src/store/pages/bossNotice/css/bossTotalNotice.module.css, src/store/pages/bossNotice/css/bossTotalNotice.module.scss, src/user/pages/reservation/components/ReservationInfo.js, src/user/pages/storedetail/components/Calendar.js
> 예약 날짜 선택 오류
<br/>
#517 
<br/>
> 예약 날짜 선택 오류
<br/>
=> [FIX][StoreDetail] 예약 날짜 선택 오류

src/config/api.config.js
> 도메인으로 변경됨에 따라 url도 변경했습니다.
<br/>
#519 
<br/>
> 
<br/>
=> [FIX][WEB] 도메인 변경으로 인한 url변경

src/admin/pages/reservation/pages/ReservationTodayInfo.js, src/admin/pages/store/pages/StoreInfo.js, src/admin/pages/store/pages/StoreInfoRegist.js, src/common/inquiry/components/DoInquiry.js, src/config/api.config.js, src/store/pages/qrCheck/pages/QrCheck.js
> qr체크인 수정 및 간단한 관리자 수정
<br/>
#521 
<br/>
> 
<br/>
=> [FIX][QR] qr체크인 수정

src/store/layouts/css/bosslayout.module.css, src/store/pages/bossInquiry/pages/TotalInquiryPage.js, src/store/pages/bossNotice/css/bossTotalNotice.module.css, src/store/pages/bossNotice/css/bossTotalNotice.module.scss, src/user/pages/reservation/components/ReservationInfo.js, src/user/pages/storedetail/components/Calendar.js, src/user/pages/storedetail/components/Menu.js, src/user/pages/storedetail/pages/Review.js
>가게 상세페이지 리뷰 없을 때 에러 
<br/>
#523 
<br/>
> 가게 상세페이지 리뷰 없을 때 에러 
<br/>
=> [FIX][StoreDetail] 가게 상세페이지 리뷰 없을 때 에러 해결

src/store/pages/bossInquiry/components/SpecificReviewModal.js, src/store/pages/bossReview/components/SpecificReview.js, src/store/pages/bossReview/pages/TotalReview.js, src/user/pages/storedetail/pages/Review.js
> api 오류 / 파라미터 오류 등등 수정
<br/>
#528 
<br/>
> api 오류 / 파라미터 오류 등등 수정
<br/>
=> [FIX][StoreDetail] api 오류 / 파라미터 오류 등등 수정

src/user/pages/signup/pages/Signup.js
> 글구 임시 수정
<br/>
#530 
<br/>
> 
<br/>
=> [FIX][SomeFix]글구 수정

src/admin/pages/dashboard/css/AdminDashboard.css, src/admin/pages/inquiry/api/StoreNoAPI.js, src/admin/pages/inquiry/css/Inquiry.module.css, src/admin/pages/inquiry/pages/InquiryInfo.js, src/admin/pages/inquiry/pages/ReportInfo.js, src/config/api.config.js
> qr, 문의리스트, 문의버튼 등 기능개선
<br/>
#539 
<br/>
> 
<br/>
=> [FIX][ADMIN] 관리자 기능 개선

package-lock.json, src/App.js, src/common/authContext/PrivateRoute.js, src/user/pages/mypage/component/MyProfile.js, src/user/pages/mypage/pages/Reservation.js, src/user/pages/mypage/pages/ReviewDetail.js
> 이슈번호 체크리스트에 설명했습니다.
<br/>
#545 
<br/>
> 금일 오프라인으로 잡힌 문제 해결 및 수정사항 반영
<br/>
=> [FIX][FixForComplement]보완 사항

package-lock.json, src/store/pages/bossStore/components/WeeklyReservationGraph.js, src/store/pages/bossStore/css/BossPage.css, src/store/pages/bossStore/pages/BossPage.js
> 그래프 구현 완료
<br/>
#544 
<br/>
> 
<br/>
=> [FIX][BOSS] 사장님 페이지 그래프 구현

src/store/pages/bossInquiry/pages/SpecificInquiry.js, src/user/pages/storedetail/pages/Review.js
> 전반적인 오류 수정
<br/>
#547 
<br/>
> 전반적인 오류 수정
<br/>
=> [FIX][Total] 전반적인 오류 수정

src/config/api.config.js, src/user/pages/main/component/Map.js
=> [FIX][ALL] 맵 수정

src/config/api.config.js
=> [MERGE][ForUpdate]

src/admin/components/AdminHeader.js, src/common/header/components/BossHeader.js, src/common/header/components/Header.js, src/user/pages/mypage/pages/ReviewDetail.js
> 로그아웃 수정
<br/>
#554 
<br/>
> 
<br/>
=> [FIX][FixLogout]로그아웃 수정

src/App.js, src/common/header/components/BossHeader.js, src/config/api.config.js, src/store/pages/bossStore/pages/BossPage.js
=> [FIX][BOSS] 사장님 페이지 에러

src/config/api.config.js, src/store/pages/bossStore/components/BasicTimePicker.js, src/store/pages/bossStore/pages/BossPage.js
=> [FIX][BOSS] 사장님 페이지 에러2

src/App.js, src/admin/components/AdminHeader.js, src/common/header/components/BossHeader.js, src/common/header/components/Header.js, src/config/api.config.js
> 배포 시 로그아웃 문제 수정
<br/>
#554 
<br/>
> 
<br/>
=> [FIX][FixLogout]배포 시 로그아웃 문제 수정

src/admin/pages/inquiry/pages/InquiryList.js, src/admin/pages/reservation/pages/ReservationList.js, src/admin/pages/review/pages/ReviewList.js, src/admin/pages/store/pages/StoreList.js, src/admin/pages/user/pages/UserList.js, src/user/pages/main/Main.js, src/user/pages/mypage/css/MyProfile.module.css, src/user/pages/mypage/css/Mypage.module.css, src/user/pages/storedetail/pages/StoreDetail.js, src/user/pages/storedetail/pages/UserStorePage.js
=> [FIX][CSS] css 수정

src/common/inquiry/css/doinquiry.css
> 폰트 등 간단한 수정
<br/>
#580 
<br/>
> 
<br/>
=> [FIX][ETC] 간단한 수정

package-lock.json, src/admin/pages/review/pages/ReviewInfo.js, src/admin/pages/store/css/StoreEdit.module.css, src/admin/pages/store/css/StoreInfo.module.css, src/admin/pages/store/css/StoreInfoRegist.module.css
> 버튼 css 수정했습니다.
<br/>
#580 
<br/>
> 
<br/>
=> [FIX][CSS] 약간의 수정

src/admin/pages/inquiry/pages/InquiryList.js, src/admin/pages/review/pages/ReviewInfo.js, src/admin/pages/review/pages/ReviewList.js
> 단어 및 약간의 수정
<br/>
#590 
<br/>
> 
<br/>
=> [FIX][ETC] 약간의 수정
